apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-xml-deployment
  labels:
    app: http-xml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-xml
  template:
    metadata:
      labels:
        app: http-xml
    spec:
      containers:
      - name: http-xml
        image: http-xml-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: http-xml-service
spec:
  selector:
    app: http-xml
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: ClusterIP
