apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-sql-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - echo.local
      # secret should be created prior to applying the Ingress (see README)
      secretName: echo-sql-tls
  rules:
    - host: echo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-sql-service
                port:
                  number: 8082
